name: nitrogen-kernel
version: 4.1.15-1
summary: Boundary Devices kernel for Nitrogen
description: Linux kernel for Boundary Devices Nitrogen platforms
type: kernel
architectures: [ armhf ]
confinement: strict
grade: stable

parts:
    kernel:
        plugin: kernel
        source: linux-imx6
        kdefconfig: [boundary_defconfig]
        kconfigs:
            - CONFIG_LOCALVERSION="-boundary-snappy"
            - CONFIG_QCA_CLD_WLAN=m
            - CONFIG_CLD_HL_SDIO_CORE=y
            - CONFIG_PRIMA_WLAN_LFR=y
            - CONFIG_PRIMA_WLAN_OKC=y
            - CONFIG_WLAN_FEATURE_11W=y
            - CONFIG_QCOM_TDLS=y
            - CONFIG_QCOM_VOWIFI_11R=y
            - CONFIG_ENABLE_LINUX_REG=y
            - CONFIG_FEATURE_NAN=y
            - CONFIG_WLAN_SYNC_TSF=y
            - CONFIG_WLAN_UDP_RESPONSE_OFFLOAD=y
            - CONFIG_WLAN_WOW_PULSE=y
        kernel-image-target: zImage
        kernel-device-trees:
            - imx6dl-nit6xlite
            - imx6dl-nitrogen6_max
            - imx6dl-nitrogen6x
            - imx6q-nitrogen6_max
            - imx6q-nitrogen6x
            - imx6qp-nitrogen6_max
            - imx6q-sabrelite
            - imx6sx-nitrogen6sx
            - imx7d-nitrogen7
        build-packages: [bc, kmod, cpio]
    firmware:
        plugin: tar-content
        source: firmware.tar
        destination: firmware
