name: nitrogen-kernel
version: 5.4.x-2.2
summary: Boundary Devices kernel for Nitrogen
description: Linux kernel for Boundary Devices Nitrogen platforms
type: kernel
build-base: core18
architectures:
  - build-on: amd64
    run-on: arm64
confinement: strict
grade: stable

parts:
    kernel:
        plugin: kernel
        source: linux-imx6
        kdefconfig: [boundary_defconfig]
        kconfigs:
            - CONFIG_LOCALVERSION="-boundary-snappy"
            - CONFIG_QCA_CLD_WLAN=m
            - CONFIG_CLD_HL_SDIO_CORE=y
            - CONFIG_PRIMA_WLAN_LFR=y
            - CONFIG_PRIMA_WLAN_OKC=y
            - CONFIG_WLAN_FEATURE_11W=y
            - CONFIG_QCOM_TDLS=y
            - CONFIG_QCOM_VOWIFI_11R=y
            - CONFIG_ENABLE_LINUX_REG=y
            - CONFIG_FEATURE_NAN=y
            - CONFIG_WLAN_SYNC_TSF=y
            - CONFIG_WLAN_UDP_RESPONSE_OFFLOAD=y
            - CONFIG_WLAN_WOW_PULSE=y
        kernel-image-target: Image
        kernel-device-trees:
            - freescale/imx8mm-nitrogen8_lite
            - freescale/imx8mm-nitrogen8mm
            - freescale/imx8mm-nitrogen8mm-m4
            - freescale/imx8mm-nitrogen8mm_rev2
            - freescale/imx8mm-nitrogen8mm_rev2-m4
            - freescale/imx8mm-nitrogen8mm_som
            - freescale/imx8mm-nitrogen8mm_som-m4
            - freescale/imx8mm-nitrogen8mm_som-mcp2518fd
            - freescale/imx8mm-nitrogen8mm_som-mcp25625
            - freescale/imx8mm-nitrogen8mm_som-tc358743
            - freescale/imx8mm-nitrogen8mm-tc358743
            - freescale/imx8mn-nitrogen8mn
            - freescale/imx8mn-nitrogen8mn_som
            - freescale/imx8mn-nitrogen8mn_som-m4
            - freescale/imx8mn-nitrogen8_nano
            - freescale/imx8mn-nitrogen8_nano-m4
            - freescale/imx8mp-nitrogen8mp
            - freescale/imx8mq-nitrogen8m
            - freescale/imx8mq-nitrogen8m-edp
            - freescale/imx8mq-nitrogen8m-m4
            - freescale/imx8mq-nitrogen8m_som
            - freescale/imx8mq-nitrogen8m_som-m4
            - freescale/imx8mq-nitrogen8m_som_sd
            - freescale/imx8mq-nitrogen8m-tc358743
            - freescale/imx8mq-nitrogen8m-tc358840
        build-packages:
            - bison
            - flex
            - libssl-dev
            - lzop
            - u-boot-tools
            - python-is-python3
        kernel-with-firmware: false
        kernel-initrd-core-base: core20
        after: [ firmware ]
    firmware:
        plugin: nil
        source: firmware
        override-build: |
            mkdir -p $SNAPCRAFT_PART_INSTALL/firmware
            cp -av ./* $SNAPCRAFT_PART_INSTALL/firmware/
